# Generated by Django 5.0.4 on 2024-04-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='club_pictures/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', 'created'],
            },
        ),
        migrations.CreateModel(
            name='loginnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddClubLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(max_length=200)),
                ('lead_name', models.CharField(max_length=200)),
                ('lead_regnumber', models.CharField(max_length=200)),
                ('lead_phonenumber', models.IntegerField()),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_program', models.CharField(max_length=200)),
                ('lead_image', models.ImageField(upload_to='lead_images/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.addclub')),
            ],
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('event_picture', models.ImageField(upload_to='event_pictures/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.addclub')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubmembers_name', models.CharField(max_length=200)),
                ('clubmembers_regnumber', models.CharField(max_length=200)),
                ('clubmembers_program', models.CharField(max_length=200)),
                ('clubmembers_phonenumber', models.IntegerField()),
                ('clubmembers_email', models.EmailField(max_length=254)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.addclub')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcomingevent_title', models.CharField(max_length=200)),
                ('upcomingevent_date', models.DateField()),
                ('upcomingevent_poster', models.ImageField(upload_to='upcoming_pictures/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.addclub')),
            ],
        ),
    ]
