# Generated by Django 5.0.4 on 2024-06-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginnn',
        ),
    ]
